# 格式版本: 1.0


# 动态缩放参数 - 前后和左右独立控制
max_longitudinal_scale: 1.5    # 前后方向最大缩放比例
min_longitudinal_scale: 0.7    # 前后方向最小缩放比例
max_lateral_scale: 1.1         # 左右方向最大缩放比例
min_lateral_scale: 0.85         # 左右方向最小缩放比例
longitudinal_sensitivity: 0.8  # 纵向灵敏度（前后方向）
lateral_sensitivity: 0.3       # 横向灵敏度（左右方向）
reference_speed: 3.0           # 参考速度(m/s)


# 车辆大小矩形各个点的位置(按顺序连接)（常规尺寸）
exigencyrect_1:
  - {x: 1.10, y: -0.30}
  - {x: 1.0, y: -0.70}
  - {x: 0.05, y: -0.70}
  - {x: 0.05, y: -0.80}
  - {x: -1.7, y: -0.80}
  - {x: -1.7, y: 0.75}
  - {x: 0.05, y: 0.75}
  - {x: 0.05, y: 0.66}
  - {x: 1.0, y: 0.66}
  - {x: 1.10, y: 0.30}

reverse_exigencyrect_1:
  - {x: 1.10, y: -0.30}
  - {x: 1.0, y: -0.70}
  - {x: 0.05, y: -0.70}
  - {x: 0.05, y: -0.80}
  - {x: -1.7, y: -0.80}
  - {x: -1.7, y: 0.75}
  - {x: 0.05, y: 0.75}
  - {x: 0.05, y: 0.66}
  - {x: 1.0, y: 0.66}
  - {x: 1.10, y: 0.30}

# 车辆大小矩形各个点的位置(按顺序连接)（窄道尺寸）
exigencyrect_2:
  - {x: 0.90, y: -0.20}
  - {x: 0.80, y: -0.52}
  - {x: -0.15, y: -0.52}
  - {x: -0.15, y: -0.75}
  - {x: -1.66, y: -0.75}
  - {x: -1.66, y: 0.65}
  - {x: -0.15, y: 0.65}
  - {x: -0.15, y: 0.56}
  - {x: 0.80, y: 0.56}
  - {x: 0.90, y: 0.20}

reverse_exigencyrect_2:
  - {x: 0.90, y: -0.20}
  - {x: 0.80, y: -0.60}
  - {x: -0.15, y: -0.60}
  - {x: -0.15, y: -0.75}
  - {x: -0.15, y: 0.67}
  - {x: -0.15, y: 0.56}
  - {x: 0.80, y: 0.56}
  - {x: 0.90, y: 0.20}

# 减速框
slowrect_1:
  - {x: 1.6, y: 0.9}
  - {x: 1.6, y: -0.9}
  - {x: -0.0, y: -1.10}
  - {x: -0.40, y: -1.12}
  - {x: -1.8, y: -1.12}
  - {x: -1.8, y: 1.12}
  - {x: -0.40, y: 1.12}
  - {x: -0.0, y: 1.10}

slowrect_2:
  - {x: 1.6, y: 0.9}
  - {x: 1.6, y: -0.9}
  - {x: -0.0, y: -1.10}
  - {x: -0.40, y: -1.12}
  - {x: -1.8, y: -1.12}
  - {x: -1.8, y: 1.12}
  - {x: -0.40, y: 1.12}
  - {x: -0.0, y: 1.10}

reverse_slowrect_1:
  - {x: 1.40, y: 0.80}
  - {x: 1.40, y: -0.80}
  - {x: -0.0, y: -1.06}
  - {x: -0.40, y: -1.08}
  - {x: -0.50, y: -1.08}
  - {x: -0.50, y: 1.08}
  - {x: -0.40, y: 1.08}
  - {x: -0.0, y: 1.06}

reverse_slowrect_2:
  - {x: 1.40, y: 0.80}
  - {x: 1.40, y: -0.80}
  - {x: -0.0, y: -1.06}
  - {x: -0.40, y: -1.08}
  - {x: -0.50, y: -1.08}
  - {x: -0.50, y: 1.08}
  - {x: -0.40, y: 1.08}
  - {x: -0.0, y: 1.06}
  
